baseurl = "https://1c0in-test.netlify.com/"
languageCode = "ja"
title = "testsite"
theme = "hugo-lithium-theme-master"

[permalinks]
    post = "/:year/:month/:day/:title/"
    page = "/:title/"

[params]
    description = ""

    [params.logo]
    url = "logo.png"
    width = 50
    height = 50
    alt = "Logo"

